---
- hosts: all
  become: yes
  tasks:
  - name: build image
    shell: docker image build -t app:latest .
  - name: Push Image to docker hub
    shell: docker tag app:latest 7385797300/app:latest
  - name: Push Image to docker hub
    shell: docker push 7385797300/app:latest

