--- 
- hosts: all
  become: yes
  tasks:
  - name: stop existing Container
	  shell: docker stop app
    ignore_errors: yes

  - name: remove the Container
	  shell: docker rm app
    ignore_errors: yes

  - name: remove image
	  shell: docker rmi krushna1512/app:latest
    ignore_errors: yes

	- name: Run Container
	  shell: docker run -d --name app -p 8080:8080 krushna1512/app:latest 

