---
- hosts: demo
  become: true
  tasks:
  - name: stop existing Container
    shell: docker stop app
    ignore_errors: yes

  - name: remove the Container
    shell: docker rm app
    ignore_errors: yes

  - name: remove image
    shell: docker rmi 7385797300/app:latest app:latest 7385797300/app
    ignore_errors: yes

  - name: Run Container
    shell: docker run -d --name app -p 8080:8080 7385797300/app:latest

